// <auto-generated />
using HellasAPIs.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HellasAPIs.Server.Migrations
{
    [DbContext(typeof(HellasDbContext))]
    [Migration("20201130020227_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HellasAPIs.Shared.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("IC_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MoneyID")
                        .HasColumnType("int");

                    b.Property<string>("SL_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SL_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterID");

                    b.HasIndex("MoneyID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consumable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Money", b =>
                {
                    b.Property<int>("MoneyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("MoneyID");

                    b.ToTable("Monies");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Stat", b =>
                {
                    b.Property<int>("StatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Const")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Int")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Str")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatsID");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Character", b =>
                {
                    b.HasOne("HellasAPIs.Shared.Money", "Money")
                        .WithMany()
                        .HasForeignKey("MoneyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Money");
                });
#pragma warning restore 612, 618
        }
    }
}
