// <auto-generated />
using HellasAPIs.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HellasAPIs.Server.Migrations
{
    [DbContext(typeof(HellasDbContext))]
    partial class HellasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HellasAPIs.Shared.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("IC_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MoneyId")
                        .HasColumnType("int");

                    b.Property<string>("SL_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SL_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.HasKey("CharacterID");

                    b.HasIndex("MoneyId");

                    b.HasIndex("StatId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consumable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Money", b =>
                {
                    b.Property<int>("MoneyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("MoneyID");

                    b.ToTable("Monies");
                });

            modelBuilder.Entity("HellasAPIs.Shared.OwnedItem", b =>
                {
                    b.Property<int>("OwnedItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OwnedItemID");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("OwnedItems");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Stat", b =>
                {
                    b.Property<int>("StatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Const")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Int")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Str")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatsID");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("HellasAPIs.Shared.Character", b =>
                {
                    b.HasOne("HellasAPIs.Shared.Money", "Money")
                        .WithMany()
                        .HasForeignKey("MoneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HellasAPIs.Shared.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Money");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("HellasAPIs.Shared.OwnedItem", b =>
                {
                    b.HasOne("HellasAPIs.Shared.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HellasAPIs.Shared.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
